M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Mon 16 Jan 2023 04:06:21 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-16T16:06:21-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X3.6Y-3.1
X3.605Y-4.29
X6.1Y-3.095
X6.1Y-4.305
T0
M30
